server:
  port: 8761

spring:
  application:
    name: discoveryservice
# microservice 의 고유한 ID 이름

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# server를 기동하기 때문에 client기능은 false로 설정