server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
#          uri: https://github.com/kihwankim/spring-cloud-example-config.git
#          private repo 일 경우 username passowrd 추가하기
#          username: abcd
#          password: abcd
          uri: file:///D:\Programs\Intellij\Programs\webprojects\class-project\sping-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
